### ISSUE TITLE
Is this for Windows?

### ISSUE THREAD

**Issue by dbruning** [madadam/freenect2.net#1]
Hi there,

I'm interested in using libfreenect2 in a c# project, and found your wrapper.
I can't see how the .so file fits in here - are you perhaps using Cygwin? Or not running on windows at all? If you had any time to flesh out the readme with some more details of how to build and use this library that would be much appreciated.

**Comment by madadam** [comment]
There is no Windows support at the moment. The project I needed this for is now finished, so I don't maintain this anymore. Feel free to fork and adapt to your needs though.

Or, if your project is Windows-only, I'd consider using the official Microsoft SDK instead.

**Comment by dbruning** [comment]
Thanks for the reply. I'm using the Microsoft SDK but exploring libfreenect2 as a way of connecting mulitple kinects. I'll have a crack at my own wrapper.

**Comment by madadam** [comment]
I think for this to work in Windows, all you need to do is compiling `native/freenect2.cpp` into a Windows DLL. So create a C++ project in Visual Studio, stick the cpp in it, and configure it to build DLL and you should be good to go. But I have very little experience with Windows development, so I might be missing something. Anyway, good luck with it!

**Comment by dbruning** [comment]
Yep it does compile to a native Windows DLL, I forgot to say that I need to use it from inside a c# app so what I really need is the c# wrapper. Time to learn c++/cli!

**Comment by madadam** [comment]
Well this project IS a C# wrapper. It just needs this native library too. So if you got that to compile on Windows, I think you should be all set.

**Comment by dbruning** [comment]
I agree in theory, but your c++ wrapper is using Make and I don't have that
setup on Windows, so having done a little reading I'm going to try the
c++/cli route. It should give a fairly similar result to your wrapper, but
I'll learn more along the way & will be able to troubleshoot better any
problems.
Great to have your wrapper available as a resource, I can see some "hacks"
in there that I'll probably need to reproduce!

On 8 March 2016 at 07:46, Adam Cigánek notifications@github.com wrote:

> Well this project IS a C# wrapper. It just needs this native library too.
> So if you got that to compile on Windows, I think you should be all set.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/madadam/freenect2.net/issues/1#issuecomment-193389416
> .

## 

Darren Bruning
027 552 5459
